name: Validate rules

on:
  workflow_call: {}

jobs:
  rules:
    name: Lint alert rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          wget https://github.com/canonical/cos-tool/releases/download/rel-20220621/cos-tool-amd64
          chmod +x ./cos-tool-amd64
      - name: Validate prometheus alert rules
        run: find . -path '*/prometheus_alert_rules/*' -type f -exec ./cos-tool-amd64 --format promql lint {} \;
      - name: Validate loki alert rules
        run: find . -path '*/loki_alert_rules/*' -type f -exec ./cos-tool-amd64 --format logql lint {} \;
