name: Pull Request

on:
  workflow_call:
    inputs:
      charm-path:
        required: false
    secrets:
       CHARMHUB_TOKEN:
         required: false
jobs:
  quality-checks:
    name: Quality Checks
    uses: canonical/observability/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
      charm-path: ${{ inputs.charm-path }}
