name: Release Charm

on:
  workflow_call:
    inputs:
      charm-path:
        description: "Path to the charm we want to publish. Defaults to the current working directory."
        default: '.'
        required: false
        type: string
      artifacts:
        description: "Json encoded list of artifacts to download before the build in the format [[name, path],...]"
        default: "[]"
        required: false
        type: string
    secrets:
      CHARMHUB_TOKEN:
        required: true

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  quality-checks:
    uses: canonical/observability/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
      charm-path: "${{ inputs.charm-path }}"
  release-charm:
    needs: 
      - quality-checks
    uses: canonical/observability/.github/workflows/_release_charm.yaml@main
    secrets: inherit
    with:
      artifacts: "${{ inputs.artifacts }}"
      charm-path: "${{ inputs.charm-path }}"
